### ISSUE TITLE
how to deal with expired contexts?

### ISSUE THREAD

**Issue by nhooyr** [codercom/retry#14]
If a retry's Context() method has been called with a context that is now expired and the retry has ended because of it, should we return the context's error or the error from the function?

At the moment, we opt for the latter, returning the error from the run function.

I think it makes more sense to return the context's error though because thats what prevented the retry from continuing.

**Comment by nhooyr** [comment]
But if we do decide to return the context's error instead of the error from the function, we should also do the same for the timeouts, where we return a error describing the timeout, not the error from the run function.

**Comment by ammario** [comment]
I think the error returned by the retry is more important than what caused the retry to finally stop.

From the debugger's perspective, the fact that the retry terminated from context cancellation or timeout is going to be obvious from the timings (and the fact it returned at all).

I'd be OK with wrapping the error based on why the retry stopped.

**Comment by nhooyr** [comment]
Fair enough, lets go with wrapping the error based on why the retry stopped.
