### ISSUE TITLE
Timeout doesn't preserve original error

### ISSUE THREAD

**Issue by ammario** [codercom/retry#23]

**Comment by nhooyr** [comment]
@ammario This was changed intentionally, the Retry finished because of the timeout not because of the error. If one wants to handle/log the error, that should be in the `Run()` function.

**Comment by ammario** [comment]
Frequently when the retry fails we want to return why it failed in the calling function. With the current design, that means creating two different error variables, and leads to confusing code.

**Comment by ammario** [comment]
Or it means we're explicitly setting an `err` variable that's outside of the retry. Equally horrible.

**Comment by ammario** [comment]
E.g https://gh.coder-internal.com/go/clide/pull/818#discussion_r14698

**Comment by nhooyr** [comment]
There are semantically two different errors here. One that caused the retry to stop and one that was returned from the last run of the function. I don't think its a good idea to conflate them. I think we add a new function `LastRunError` to get the the error from the last call to the Run function.
